#!/bin/bash -e
# Use CloudFront to discover application name and push there

[[ -n "${verbose:-}" ]] && set -x

APP_KEY="codedeploy/Techscore.zip"

get-cf-export-value() {
    aws cloudformation list-exports --output text --query "Exports[?Name==\`$1\`].Value"
}

get-app-name() {
    get-cf-export-value CodeDeployApp
}

get-code-bucket() {
    get-cf-export-value CodeBucket
}

get-my-dir() {
    cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd
}

execute() {
    cd $(get-my-dir)/techscore
    aws deploy push \
        --application-name=$(get-app-name) \
        --s3-location s3://$(get-code-bucket)/$APP_KEY \
        --ignore-hidden-files
}

(execute)
