#!/bin/bash

APP_BUCKET="techscore-app.openweb"
APP_KEY="codedeploy/Techscore.zip"

get-cf-export-value() {
    aws cloudformation list-exports --output text --query "Exports[?Name==\`$1\`].Value"
}

get-app-name() {
    get-cf-export-value CodeDeployApp
}

get-deployment-group() {
    get-cf-export-value CodeDeploymentGroup
}

get-md5sum() {
    aws s3api head-object --bucket $APP_BUCKET --key $APP_KEY --output text --query ETag | tr -d '"'
}

execute() {
    aws deploy create-deployment \
        --application-name $(get-app-name) \
        --s3-location bucket=$APP_BUCKET,key=$APP_KEY,bundleType=zip,eTag=$(get-md5sum) \
        --deployment-group-name $(get-deployment-group)
}

execute
