# Techscore webserver running Apache, PHP and connecting to MySQL
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Launches an EC2 instance into private subnet'

Parameters:
  KeyPair:
    Type: String
    Description: Fallback key pair to use
    Default: ""

Conditions: 
  UseKeyPair: !Not [!Equals [!Ref KeyPair, ""]]

Mappings:
  RegionMap:
    us-west-2:
      AMI: 'ami-f2d3638a'

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Metadata:
      Comment1: 'Configure instance to use SSM for public keys'
      AWS::CloudFormation::Init:
        configSets:
          Install:
            - CloudInitSetup
            - InstallAuthorizedKeysCommand
            - SetupWebServer

        CloudInitSetup:
          files:
            '/etc/cfn/cfn-hup.conf':
              content:
                Fn::Sub: |
                  [main]
                  stack=${AWS::StackId}
                  region=${AWS::Region}
                  verbose=true
              mode: '000400'
              owner: root
              group: root
            '/etc/cfn/hooks.d/cfn-auto-reloader.conf':
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.WebServer.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServer --configsets Install --region ${AWS::Region}
                runas=root
              mode: '000400'
              owner: root
              group: root

          services:
            sysvinit:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - /etc/cfn/cfn-hup.conf
                sources:
                  - /etc/cfn/hooks.d

        InstallAuthorizedKeysCommand:
          files:
            '/usr/local/bin/ssm-public-key.sh':
              content:
                Fn::Sub: |
                  #!/bin/bash -xe
                  aws --region ${AWS::Region} ssm get-parameter --name /SSH/publickey --output text --query Parameter.Value
              mode: '000555'
          commands:
            modifyConfig:
              command: |
                echo >> /etc/ssh/sshd_config
                echo 'AuthorizedKeysCommand /usr/local/bin/ssm-public-key.sh' >> /etc/ssh/sshd_config
                echo 'AuthorizedKeysCommandUser ec2-user' >> /etc/ssh/sshd_config
            restartSsh:
              command: '/etc/init.d/sshd restart'

        SetupWebServer:
          packages:
            yum:
              php54: []
              php54-mysqlnd: []
              php54-mbstring: []
              php54-common: []
              php54-cli: []
              php54-xml: []
              php54-pdo: []
              php54-process: []
              git: []
          files:
            '/etc/httpd/conf.d/ows-sites.conf':
              content: |
                <Directory /srv>
                  Require all granted
                </Directory>
                IncludeOptional sites/*.conf
              mode: '000644'

          commands:
            100createSessionsDir:
              command: |
                mkdir /etc/httpd/sessions
                chown apache:apache /etc/httpd/sessions
                chmod 770 /etc/httpd/sessions

            200createSitesDir:
              command: mkdir /etc/httpd/sites

            900restartApache:
              command: /etc/init.d/httpd restart
          users:
            techscore:
              groups:
                - wheel
    Properties:
      ImageId:
        Fn::FindInMap:
          - RegionMap
          - Ref: AWS::Region
          - AMI
      IamInstanceProfile: !ImportValue WebServerInstanceProfile
      InstanceType: t2.medium
      KeyName:
        Fn::If:
          - UseKeyPair
          - Ref: KeyPair
          - Ref: AWS::NoValue
      SubnetId: !ImportValue PrivateSubnet1
      SecurityGroupIds:
        - !ImportValue WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: WebServer
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -xe
            yum update -y
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServer --configsets Install --region ${AWS::Region}
