# Techscore on AWS: Public scores site
---
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for public scores and CloudFront distribution
Parameters:
  OrgHostname:
    Type: String
    Description: |
      Top-level domain name for organization (i.e. collegesailing.org). For the
      public site, scores. will be prepended. For the private site, ts. instead.

  ScoresSubdomain:
    Type: String
    Description: Subdomain of OrgHostname for public site
    Default: scores
    AllowedPattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]$

  ScoresCertificateArn:
    Type: String
    Description: ARN of certificate for the public site

Resources:
  Scores:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html

  PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Scores
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${Scores.Arn}/*'

  CFDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Select [2, !Split ['/', !GetAtt [Scores, WebsiteURL]]]
            Id: ScoresBucketOrigin
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only

        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - Fn::Sub: '${ScoresSubdomain}.${OrgHostname}'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: ScoresBucketOrigin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: 'redirect-to-https'
          DefaultTTL: 30
          MinTTL: 0
          MaxTTL: 300
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref ScoresCertificateArn
          SslSupportMethod: sni-only

Outputs:
  ScoresBucketArn:
    Description: ARN for the bucket where scores are uploaded.
    Value: !GetAtt [Scores, Arn]
    Export:
      Name: ScoresBucketArn
