# Techscore on AWS: DB setup
---
AWSTemplateFormatVersion: '2010-09-09'
Description: |
  OpenWeb Solution's Techscore application with RDS backing.

Parameters:
  OrgHostname:
    Type: String
    Description: |
      Top-level domain name for organization (i.e. collegesailing.org). For the
      public site, scores. will be prepended. For the private site, ts. instead.

  DBUsername:
    Type: String
    Description: Master username
    Default: techscore

  DBPassword:
    Type: String
    Description: Master password
    Default: csail04sailor2
    NoEcho: true

Resources:
  # RDS
  DBEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Open database for access'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !ImportValue WebServerSecurityGroup
      VpcId: !ImportValue VpcId
      Tags:
        - Key: Name
          Value: !Sub '${OrgHostname} - DB'

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets available to DB
      SubnetIds:
        - !ImportValue PrivateSubnet1
        - !ImportValue PrivateSubnet2

  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      Engine: aurora-mysql
      DBClusterParameterGroupName: default.aurora-mysql5.7
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - Ref: DBEC2SecurityGroup

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Enables log_bin_trust_function_creators to allow mysqldump
      Family: aurora-mysql5.7
      Parameters:
        log_bin_trust_function_creators: 1

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: 'aurora-mysql'
      DBClusterIdentifier: !Ref DBCluster
      DBParameterGroupName: !Ref DBParameterGroup
      PubliclyAccessible: false
      MultiAZ: false
      DBInstanceClass: db.t2.small

Outputs:
  DBHost:
    Description: Host for the DB instance
    Value: !GetAtt [DBInstance, Endpoint.Address]
    Export:
      Name: DBHost
