# Techscore on AWS: Certificate request for public site, which MUST BE
# RUN against us-east-1
---
AWSTemplateFormatVersion: '2010-09-09'
Description: Certificates for public and private site
Parameters:
  OrgHostname:
    Type: String
    Description: |
      Top-level domain name for organization (i.e. collegesailing.org). For the
      public site, scores. will be prepended. For the private site, ts. instead.

  ScoresSubdomain:
    Type: String
    Description: Subdomain of OrgHostname for public site
    Default: scores
    AllowedPattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]$

Resources:
  ScoresCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName:
        Fn::Sub: '${ScoresSubdomain}.${OrgHostname}'
      DomainValidationOptions:
        - DomainName:
            Fn::Sub: '${ScoresSubdomain}.${OrgHostname}'
          ValidationDomain: !Ref OrgHostname

Outputs:
  ScoresCertificateArn:
    Description: ARN for the created certificate for scores domain.
    Value: !Ref ScoresCertificate
    Export:
      Name: ScoresCertificateArn
